{{- if eq .Values.global.storage "minio" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-minio
  labels:
    heritage: deis
  annotations:
    component.deis.cc/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      serviceAccount: deis-minio
      containers:
        - name: deis-minio
          image: quay.io/{{.Values.org}}/minio:{{.Values.docker_tag}}
          imagePullPolicy: {{.Values.pull_policy}}
          env:
            - name: STORAGE
              value: "{{.Values.global.storage}}"
          ports:
            - containerPort: 9000
          command:
            - boot
          args:
            - "server /home/minio/"
          volumeMounts:
            - name: objectstore-creds
              mountPath: /var/run/secrets/deis/objectstore/creds
              readOnly: true
      volumes:
        - name: objectstore-creds
          secret:
            secretName: objectstorage-keyfile
{{- end }}
